# Generated by Django 5.2.7 on 2025-10-15 06:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nombre')),
                ('icon', models.CharField(blank=True, help_text='Clase de icono (ej. fa-wifi)', max_length=50, verbose_name='icono')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'comodidad',
                'verbose_name_plural': 'comodidades',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nombre')),
                ('category', models.CharField(choices=[('BASIC', 'Básica'), ('STANDARD', 'Estándar'), ('PREMIUM', 'Premium'), ('LUXURY', 'De Lujo'), ('SUITE', 'Suite')], default='STANDARD', max_length=20, verbose_name='categoría')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='precio por noche')),
                ('number_of_beds', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='número de camas')),
                ('room_capacity', models.PositiveIntegerField(help_text='Capacidad máxima de personas', validators=[django.core.validators.MinValueValidator(1)], verbose_name='capacidad')),
                ('total_rooms', models.PositiveIntegerField(help_text='Cantidad total de habitaciones de este tipo', validators=[django.core.validators.MinValueValidator(1)], verbose_name='total de habitaciones')),
                ('description', models.TextField(verbose_name='descripción')),
                ('image', models.ImageField(blank=True, null=True, upload_to='room_types/', verbose_name='imagen')),
                ('size_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='tamaño (m²)')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('amenities', models.ManyToManyField(blank=True, related_name='room_types', to='rooms.amenity', verbose_name='comodidades')),
            ],
            options={
                'verbose_name': 'tipo de habitación',
                'verbose_name_plural': 'tipos de habitación',
                'ordering': ['category', 'price_per_night'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(help_text='Identificador único de la habitación (ej. 101, 205)', max_length=10, unique=True, verbose_name='número de habitación')),
                ('floor', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='piso')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Disponible'), ('OCCUPIED', 'Ocupada'), ('MAINTENANCE', 'Mantenimiento'), ('CLEANING', 'Limpieza')], default='AVAILABLE', max_length=20, verbose_name='estado')),
                ('is_available', models.BooleanField(default=True, help_text='Disponibilidad para reservas', verbose_name='disponible')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='rooms.roomtype', verbose_name='tipo de habitación')),
            ],
            options={
                'verbose_name': 'habitación',
                'verbose_name_plural': 'habitaciones',
                'ordering': ['room_number'],
            },
        ),
        migrations.AddIndex(
            model_name='roomtype',
            index=models.Index(fields=['category', 'is_active'], name='rooms_roomt_categor_bd587f_idx'),
        ),
        migrations.AddIndex(
            model_name='roomtype',
            index=models.Index(fields=['price_per_night'], name='rooms_roomt_price_p_2e8de5_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['room_number'], name='rooms_room_room_nu_914a74_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['status', 'is_available'], name='rooms_room_status_32e42b_idx'),
        ),
    ]
