# Generated by Django 5.2.7 on 2025-10-15 06:14

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('address', models.TextField(verbose_name='dirección')),
                ('city', models.CharField(max_length=100, verbose_name='ciudad')),
                ('state', models.CharField(max_length=100, verbose_name='estado')),
                ('postal_code', models.CharField(max_length=10, verbose_name='código postal')),
                ('phone', models.CharField(max_length=20, verbose_name='teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('description', models.TextField(verbose_name='descripción')),
                ('check_in_time', models.TimeField(default='15:00', verbose_name='hora de check-in')),
                ('check_out_time', models.TimeField(default='12:00', verbose_name='hora de check-out')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
            ],
            options={
                'verbose_name': 'hotel',
                'verbose_name_plural': 'hoteles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código único del cupón', max_length=50, unique=True, verbose_name='código')),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Porcentaje'), ('FIXED', 'Monto Fijo')], default='PERCENTAGE', max_length=20, verbose_name='tipo de descuento')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='valor del descuento')),
                ('min_amount', models.DecimalField(decimal_places=2, default=0, help_text='Monto mínimo de reserva para aplicar el cupón', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='monto mínimo')),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, help_text='Descuento máximo aplicable (solo para porcentajes)', max_digits=10, null=True, verbose_name='descuento máximo')),
                ('valid_from', models.DateTimeField(verbose_name='válido desde')),
                ('valid_until', models.DateTimeField(verbose_name='válido hasta')),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Número máximo de veces que puede usarse el cupón', null=True, verbose_name='usos máximos')),
                ('times_used', models.PositiveIntegerField(default=0, verbose_name='veces usado')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
            ],
            options={
                'verbose_name': 'cupón',
                'verbose_name_plural': 'cupones',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code', 'is_active'], name='bookings_co_code_ee88da_idx')],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='ID de reserva')),
                ('invoice_id', models.CharField(editable=False, max_length=100, unique=True, verbose_name='ID de factura')),
                ('check_in_date', models.DateField(verbose_name='fecha de check-in')),
                ('check_out_date', models.DateField(verbose_name='fecha de check-out')),
                ('booking_date', models.DateTimeField(auto_now_add=True, verbose_name='fecha de reserva')),
                ('adults', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='adultos')),
                ('children', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='niños')),
                ('special_requests', models.TextField(blank=True, help_text='Necesidades especiales o preferencias', verbose_name='solicitudes especiales')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='subtotal')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='descuento')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='impuestos')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='precio total')),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PAID', 'Pagado'), ('CONFIRMED', 'Confirmado'), ('CANCELLED', 'Cancelado'), ('REFUNDED', 'Reembolsado')], default='PENDING', max_length=20, verbose_name='estado de pago')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='rooms.room', verbose_name='habitación')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='bookings.coupon', verbose_name='cupón')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='bookings.hotel', verbose_name='hotel')),
            ],
            options={
                'verbose_name': 'reservación',
                'verbose_name_plural': 'reservaciones',
                'ordering': ['-booking_date'],
                'indexes': [models.Index(fields=['user', 'payment_status'], name='bookings_bo_user_id_93b31a_idx'), models.Index(fields=['check_in_date', 'check_out_date'], name='bookings_bo_check_i_64cf26_idx'), models.Index(fields=['hotel', 'payment_status'], name='bookings_bo_hotel_i_0843b5_idx'), models.Index(fields=['booking_id'], name='bookings_bo_booking_eb8fc3_idx')],
            },
        ),
    ]
